version: "3.8"

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: nginx_image
    networks:
      - app_network
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/nginx.conf.template
    working_dir: /usr/share/nginx/html
    command: /bin/bash -c "envsubst '${APP_PORT} ${PORTAINER_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/conf.d/nginx.conf && nginx -g 'daemon off;'"
    environment:
      - APP_PORT=${APP_PORT}
      - PORTAINER_PORT=9000

  backend:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: backend
    image: backend_image
    networks:
      - app_network
    ports:
      - "${APP_PORT}:8088"
    depends_on:
      - database
    environment:
      - DB_DRIVER=${DB_DRIVER}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - CLIENT_ORIGIN=${CLIENT_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
      - APP_PORT=${APP_PORT}
      - APP_ENV=${APP_ENV}
      - AWS_REGION=${AWS_REGION}
      - SECRET_MANAGER_KEY=${SECRET_MANAGER_KEY}
     
  database:
    build: 
      context: docker/mysql
      dockerfile: Dockerfile
    container_name: mysql
    image: mysql_image
    networks:
      - app_network
    volumes:
      - app_db_volume:/var/lib/mysql
    environment:
      - MYSQL_USER=duongdx
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - "${DB_PORT}:3306"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    networks:
      - app_network
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  app_network:
    name: app_network

volumes:
  app_db_volume: {}
  portainer_data: {}
